name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-java:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v3
        with:
          name: app # Asegúrate de que este nombre sea consistente
          path: target/*.jar

  build-docker:
    needs: build-java
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download JAR artifact
        uses: actions/download-artifact@v3
        with:
          name: app # Debe coincidir con el nombre usado en el paso anterior

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t duvangt/anderson-maldonado:v1.0 .

      - name: Push Docker image
        run: docker push duvangt/anderson-maldonado:v1.0
